import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import DisplayContent from '../components/DisplayContent'
import MainForm from '../components/MainForm'
import styles from '../styles/Home.module.css'

export const API_URL = 'https://6166c4e213aa1d00170a670e.mockapi.io/information'

export default function Home() {
	const [isDisplayPage, setIsDisplayPage] = useState(true)

	const handleSwitch = () => {
		setIsDisplayPage(false)
	}

	const getDisplayPage = () => {
		setIsDisplayPage(true)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Bookmark-App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				{isDisplayPage ? (
					<DisplayContent onClick={handleSwitch} />
				) : (
					<MainForm handlePageChange={getDisplayPage} />
				)}
			</main>
		</div>
	)
}
